export const listProjects = [
    {
        id: 0,
        name: "Projeto Clima",
        image: "src/assets/projects/clima.png",
        link: "https://othurdev.github.io/projeto-clima/",
        javascript: true,
        html: true,
        css:true,
        reactJs: false,
        typeScript: false,
        laravel: false,
        tailwind: false,
        styled: false
    },
    {
        id: 1,
        name: "Jogo da Velha",
        image: "src/assets/projects/velha.png",
        link: "https://othurdev.github.io/projeto-jogo-da-velha/",
        javascript: true,
        html: true,
        css:true,
        reactJs: false,
        typeScript: false,
        laravel: false,
        tailwind: false,
        styled: false
    },
    {
        id: 2,
        name: "Arrasta e Solta",
        image: "src/assets/projects/arrasta.png",
        link: "https://othurdev.github.io/projeto-arrasta-e-solta/",
        javascript: true,
        html: true,
        css:true,
        reactJs: false,
        typeScript: false,
        laravel: false,
        tailwind: false,
        styled: false
    },
    {
        id: 3,
        name: "Starbucks",
        image: "src/assets/projects/starbucks.png",
        link: "https://othurdev.github.io/projeto-starbucks/",
        javascript: true,
        html: true,
        css:true,
        reactJs: false,
        typeScript: false,
        laravel: false,
        tailwind: false,
        styled: false
    },
    {
        id: 4,
        name: "Quadro de Desenho",
        image: "src/assets/projects/desenho.png",
        link: "https://othurdev.github.io/projeto-quadro-de-desenho/",
        javascript: true,
        html: true,
        css:true,
        reactJs: false,
        typeScript: false,
        laravel: false,
        tailwind: false,
        styled: false
    },
    {
        id: 5,
        name: "Bateria",
        image: "src/assets/projects/bateria.png",
        link: "https://othurdev.github.io/projeto-bateria/",
        javascript: true,
        html: true,
        css:true,
        reactJs: false,
        typeScript: false,
        laravel: false,
        tailwind: false,
        styled: false
    },
]